/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_jcy_jni_JniTest */

#ifndef _Included_com_jcy_jni_JniTest
#define _Included_com_jcy_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcy_jni_JniTest
 * Method:    getString2FromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jcy_jni_JniTest_getString2FromC
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jcy_jni_JniTest_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jcy_jni_JniTest_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_accessMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_accessStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    accessConstructor
 * Signature: ()Ljava/sql/Date;
 */
JNIEXPORT jobject JNICALL Java_com_jcy_jni_JniTest_accessConstructor
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    accessNonvirtualMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_accessNonvirtualMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    chineseChars
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jcy_jni_JniTest_chineseChars
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    giveArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_giveArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    getArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jcy_jni_JniTest_getArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    localRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_localRef
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    createGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_createGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    getGlobalRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jcy_jni_JniTest_getGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    deleteGlobalRef
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_deleteGlobalRef
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    exeception
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_exeception
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    cached
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_cached
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_jni_JniTest
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_jni_JniTest_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
