/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcy_ndk_nativeC_qqvoice_AudioProcess */

#ifndef _Included_com_jcy_ndk_nativeC_qqvoice_AudioProcess
#define _Included_com_jcy_ndk_nativeC_qqvoice_AudioProcess
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_NORMAL
#define com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_NORMAL 0L
#undef com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_LUOLI
#define com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_LUOLI 1L
#undef com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_DASHU
#define com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_DASHU 2L
#undef com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_JINGSONG
#define com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_JINGSONG 3L
#undef com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_GAOGUAI
#define com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_GAOGUAI 4L
#undef com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_KONGLING
#define com_jcy_ndk_nativeC_qqvoice_AudioProcess_MODE_KONGLING 5L
/*
 * Class:     com_jcy_ndk_nativeC_qqvoice_AudioProcess
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_qqvoice_AudioProcess_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
