/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcy_ndk_nativeC_basic_PosixThread */

#ifndef _Included_com_jcy_ndk_nativeC_basic_PosixThread
#define _Included_com_jcy_ndk_nativeC_basic_PosixThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcy_ndk_nativeC_basic_PosixThread
 * Method:    pthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_basic_PosixThread_pthread
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_ndk_nativeC_basic_PosixThread
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_basic_PosixThread_init
  (JNIEnv *, jobject);

/*
 * Class:     com_jcy_ndk_nativeC_basic_PosixThread
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_basic_PosixThread_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
