/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer */

#ifndef _Included_com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer
#define _Included_com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer_sound
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer
 * Method:    play
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer_play
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer
 * Method:    push
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_ffmpeg_FFmpegPalyer_push
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
