/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcy_ndk_nativeC_ffmpeg_OpenSL_ES_AudioPlayer */

#ifndef _Included_com_jcy_ndk_nativeC_ffmpeg_OpenSL_ES_AudioPlayer
#define _Included_com_jcy_ndk_nativeC_ffmpeg_OpenSL_ES_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcy_ndk_nativeC_ffmpeg_OpenSL_ES_AudioPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_ffmpeg_OpenSL_1ES_1AudioPlayer_play
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
