/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcy_ndk_nativeC_basic_NDKFileUtils */

#ifndef _Included_com_jcy_ndk_nativeC_basic_NDKFileUtils
#define _Included_com_jcy_ndk_nativeC_basic_NDKFileUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcy_ndk_nativeC_basic_NDKFileUtils
 * Method:    split
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_basic_NDKFileUtils_split
        (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_jcy_ndk_nativeC_basic_NDKFileUtils
 * Method:    patch
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jcy_ndk_nativeC_basic_NDKFileUtils_patch
        (JNIEnv *, jclass, jstring, jint);
}