/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcy_ndk_nativeC_basic_HelloLibrary */

#ifndef _Included_com_jcy_ndk_nativeC_basic_HelloLibrary
#define _Included_com_jcy_ndk_nativeC_basic_HelloLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcy_ndk_nativeC_basic_HelloLibrary
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jcy_ndk_nativeC_basic_HelloLibrary_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
